project_id = "ufvupwnhpqeexadmqajk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.get-crypto-price]
verify_jwt = false

[functions.manage-fast-pools]
verify_jwt = false

[functions.calc-pools-with-rewards]
verify_jwt = false

[functions.cancel-limit-order]
verify_jwt = true

[functions.close-expired-markets]
verify_jwt = false

[functions.create-support-ticket]
verify_jwt = true

[functions.exchange-convert]
verify_jwt = true

[functions.execute-limit-orders-v2]
verify_jwt = false

[functions.execute-limit-orders]
verify_jwt = false

[functions.execute-market-order]
verify_jwt = true

[functions.get-cashout-quote]
verify_jwt = true

[functions.get-history]
verify_jwt = true

[functions.get-orderbook-depth]
verify_jwt = false

[functions.get-orderbook]
verify_jwt = false

[functions.get-rate]
verify_jwt = false

[functions.liquidate-market-improved]
verify_jwt = false

[functions.liquidate-market]
verify_jwt = false

[functions.perform-cashout]
verify_jwt = true

[functions.populate-rates-history]
verify_jwt = false

[functions.process-fiat-request]
verify_jwt = true

[functions.reconcile-balances]
verify_jwt = false

[functions.test-reconciliation]
verify_jwt = false

[functions.validate-exchange-reconciliation]
verify_jwt = false

[functions.validate-reconciliation]
verify_jwt = false