project_id = "ufvupwnhpqeexadmqajk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# Edge Functions
[functions.close-expired-markets]
verify_jwt = false

[functions.get-cashout-quote]
verify_jwt = true

[functions.perform-cashout]
verify_jwt = true

[functions.calc-pools-with-rewards]
verify_jwt = false

[functions.liquidate-market]
verify_jwt = false

[functions.liquidate-market-improved]
verify_jwt = false

[functions.get-rate]
verify_jwt = false

[functions.exchange-convert]
verify_jwt = true

[functions.get-history]
verify_jwt = true

[functions.execute-limit-orders]
verify_jwt = false

[functions.validate-reconciliation]
verify_jwt = true

[functions.test-reconciliation]
verify_jwt = true

[functions.execute-limit-orders-v2]
verify_jwt = false

[functions.validate-exchange-reconciliation]
verify_jwt = true