// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufvupwnhpqeexadmqajk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdnVwd25ocHFlZXhhZG1xYWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODg3NjYsImV4cCI6MjA3NDE2NDc2Nn0.iL0h7rYwsmhx8XhSOhbiu4gwFw4YewbNPkn4WUdtBWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});